# Generated by Django 4.1.3 on 2022-12-05 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year_of_release',
            field=models.IntegerField(default=1990, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1930)]),
            preserve_default=False,
        ),
    ]
