# Generated by Django 4.1.3 on 2022-12-05 16:11

from django.db import migrations, models
import watch_demo.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('comedy', 'Comedy'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('sci_fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('western', 'Western')], default='Horror', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(upload_to='movie_posters/', validators=[watch_demo.core.validators.validate_file_less_than_5mb]),
        ),
    ]
