# Generated by Django 4.1.3 on 2022-12-10 13:44

from django.db import migrations, models
import watch_demo.core.model_mixin
import watch_demo.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[watch_demo.core.validators.validate_only_letters])),
            ],
            bases=(watch_demo.core.model_mixin.StrFromFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagged_actors',
            field=models.ManyToManyField(blank=True, null=True, to='movies.actor'),
        ),
    ]
