# Generated by Django 4.1.3 on 2022-12-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_actor_movie_tagged_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagged_actors',
            field=models.ManyToManyField(blank=True, to='movies.actor'),
        ),
    ]
