# Generated by Django 4.1.3 on 2022-12-10 14:07

from django.db import migrations, models
import watch_demo.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_tagged_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='actor',
            name='last_name',
            field=models.CharField(default='', max_length=30, validators=[watch_demo.core.validators.validate_only_letters]),
            preserve_default=False,
        ),
    ]
