# Generated by Django 4.1.3 on 2022-12-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_name_actor_first_name_actor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagged_actors',
            field=models.ManyToManyField(to='movies.actor'),
        ),
    ]
