# Generated by Django 4.1.3 on 2022-12-15 13:38

import django.core.validators
from django.db import migrations, models
import watch_demo.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_tagged_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_of_release',
            field=models.IntegerField(validators=[watch_demo.core.validators.validate_year]),
        ),
    ]
