# Generated by Django 4.1.3 on 2022-12-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_name_alter_movie_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-year_of_release',)},
        ),
    ]
